@echo off
echo Starting deployment to both remotes...
git add .
git commit -m "Production stability: Aggressive CORS, image uploads, and data sync fixes"
echo Pushing to frontend remote (heroku)...
git push heroku main:master
echo Pushing to backend remote (heroku-api)...
git push heroku-api main:master
echo Deployment finished with exit code %errorlevel%
